apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 10hin@outlook.jp
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - argocd-github-sso.eks.10h.in
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z0549193OI7AWVFXVBMB
