apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd-github-sso
  region: ap-northeast-1

availabilityZones:
  - ap-northeast-1a
  - ap-northeast-1c

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: secrets-manager
        namespace: argocd
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - arn:aws:secretsmanager:ap-northeast-1:129008548655:secret:argocd-github-sso-github-oauth-app-XkY8Iy
              - arn:aws:secretsmanager:ap-northeast-1:129008548655:secret:argocd-github-sso-argocd-M4a4WM

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: argocd
      - namespace: external-secrets
