apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: albc
  namespace: argocd
spec:
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: '1.6.0'
    helm:
      releaseName: albc
      parameters:
        - name: clusterName
          value: argocd-github-sso
        - name: serviceAccount.create
          value: 'false'
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - # aws eks describe-cluster --name argocd-github-sso --query 'cluster.resourcesVpcConfig.vpcId' --output text
          name: vpcId
          value: vpc-05abb589ebfbb1e0b
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
