apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: argocd-sercret
    creationPolicy: Merge
    deletionPolicy: Merge
    template:
      data:
        webhook.github.secret: '{{ .secret }}'
  data:	
    - secretKey: secret
      remoteRef:	
        key: argocd-github-sso-github-webhook
        property: SECRET
