apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: github-webhook
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        secret: '{{ .secret }}'
  data:	
    - secretKey: secret
      remoteRef:	
        key: argocd-github-sso-github-webhook
        property: SECRET
