apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: id-source
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: id-source
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        dex.github.clientSecret: '{{ .clientSecret }}'
  data:	
    - secretKey: clientSecret
      remoteRef:	
        key: argocd-github-sso-github-oauth-app
        property: CLIENT_SECRET
