apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - albc-application.yaml
  - argocd-application.yaml
  # when spin-up: uncomment "argocd-ingress.yaml" to create ALB for ArgoCD
  # when tear-down: comment out "argocd-ingress.yaml" to delete ALB for ArgoCD
  - argocd-ingress.yaml
  - argogrpc-service.yaml
  - coredns-application.yaml
  - external-secrets-application.yaml
  - install.yaml
  - manifest-source-externalsecret.yaml
  - namespaces-application.yaml
  - secrets-manager-secretstore.yaml
  - id-source-externalsecret.yaml
  - external-dns-application.yaml
  # - cert-manager-application.yaml
  # - cert-issuer-application.yaml
  - github-webhook-externalsecret.yaml

patches:
  - path: argocd-server-service.yaml
  - path: argocd-cm-configmap.yaml
  - path: argocd-secret-secret.yaml
