apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - albc-application.yaml
  - argocd-application.yaml
  # - argocd-ingress.yaml
  - argogrpc-service.yaml
  - coredns-application.yaml
  - external-secrets-application.yaml
  - install.yaml
  - manifest-source-externalsecret.yaml
  - namespaces-application.yaml
  - secrets-manager-secretstore.yaml
  - id-source-externalsecret.yaml
  - external-dns-application.yaml

patches:
  - path: argocd-server-service.yaml
  - path: argocd-cm-configmap.yaml
