apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manifest-source
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: manifest-source
    creationPolicy: Owner
  template:
    data:
      type: git
      url: https://github.com/10hin/argocd-github-sso.git
      username: 10hin
      password: '{{ .password }}'
  data:	
    - secretKey: password
      remoteRef:	
        key: argocd-github-sso-argocd
        property: GITHUB_TOKEN
