apiVersion: v1
kind: Secret
metadata:
  name: manifest-source
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/10hin/argocd-github-sso.git
