apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manifest-source
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: manifest-source
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 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
        property: GITHUB_TOKEN
