apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets-manager
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-manager
